version: '3'
services:
    app:
        build: ./docker/app
        volumes:
            - ./src/:/var/www/html
        container_name: php
    web:
        image: nginx:1.25
        container_name: nginx
        ports:
            - 8000:80 
        volumes:
            - ./src:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/html
        depends_on:
            - app
    db:
        image: postgres:16.0
        container_name: postgres
        ports:
          - 5432:5432
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=Rootp123@
          - POSTGRES_DB=lumen
        volumes:
          - /var/lib/postgresql/data
